# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]
                version: ['1.45.1']

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run compile --if-present

            - name: Start xvfb
            if: startsWith(matrix.os, 'ubuntu')
            run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

            - name: Run tests
            env:
                CODE_VERSION: ${{ matrix.version }}
                DISPLAY: ':99.0'
            run: npm test
